
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run building with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run installing dependencies
      run: npm install

    - name: Install hexo
      run: npm install hexo

    - name: Generate pages
      run: hexo generate

    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v2.0.1
      with:
        # zeit.co token
        zeit-token: ${{ secrets.ZEIT_TOKEN }}